import React, { useEffect, useState } from 'react';
import confetti from 'canvas-confetti';
import { 
  Award, 
  Download, 
  Copy, 
  Check, 
  RotateCcw, 
  TrendingUp, 
  Target, 
  CheckCircle2, 
  AlertTriangle,
  Lightbulb,
  FileText,
  Star
} from 'lucide-react';

export default function EvaluationView({
  reportText,
  interviewType,
  totalQuestions,
  onResetSession
}) {
  const [copied, setCopied] = useState(false);

  // Trigger celebration confetti
  useEffect(() => {
    try {
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 }
      });
    } catch (e) {}
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AIVA_Interview_Evaluation_${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <section className="app-container" style={{ paddingBottom: '5rem' }}>
      {/* Header */}
      <div className="evaluation-hero">
        <div className="hero-pill" style={{ color: 'var(--accent-emerald)', borderColor: 'rgba(16, 185, 129, 0.4)', background: 'rgba(16, 185, 129, 0.1)' }}>
          <Award size={15} />
          <span>Interview Session Successfully Concluded</span>
        </div>
        <h1>Performance Assessment & Feedback</h1>
        <p className="hero-subtitle">
          Review your strengths, weaknesses, and concrete recommendations generated by your AI Interviewer.
        </p>
      </div>

      {/* Score Grid Cards */}
      <div className="score-grid">
        <div className="score-box">
          <div className="score-number">88<span style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>/100</span></div>
          <div style={{ fontWeight: 600, color: 'white', fontSize: '1.05rem', marginBottom: '0.2rem' }}>
            Overall Performance
          </div>
          <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            Strong technical foundation with clear potential
          </div>
        </div>

        <div className="score-box emerald">
          <div className="score-number">85<span style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>%</span></div>
          <div style={{ fontWeight: 600, color: 'white', fontSize: '1.05rem', marginBottom: '0.2rem' }}>
            Technical Depth
          </div>
          <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            Demonstrated good conceptual grasp
          </div>
        </div>

        <div className="score-box">
          <div className="score-number">92<span style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>%</span></div>
          <div style={{ fontWeight: 600, color: 'white', fontSize: '1.05rem', marginBottom: '0.2rem' }}>
            Communication & Tone
          </div>
          <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            Articulate, calm, and professional delivery
          </div>
        </div>

        <div className="score-box">
          <div className="score-number">86<span style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>%</span></div>
          <div style={{ fontWeight: 600, color: 'white', fontSize: '1.05rem', marginBottom: '0.2rem' }}>
            Problem Solving
          </div>
          <div style={{ fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            Systematic reasoning through questions
          </div>
        </div>
      </div>

      {/* Action Toolbar */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginBottom: '1.5rem' }}>
        <button className="btn btn-secondary" onClick={handleCopy}>
          {copied ? <Check size={16} /> : <Copy size={16} />}
          <span>{copied ? 'Copied to Clipboard!' : 'Copy Evaluation'}</span>
        </button>

        <button className="btn btn-secondary" onClick={handleDownload}>
          <Download size={16} />
          <span>Download Markdown (.md)</span>
        </button>

        <button className="btn btn-primary" onClick={onResetSession}>
          <RotateCcw size={16} />
          <span>Start Another Interview</span>
        </button>
      </div>

      {/* Formatted Evaluation Report Content */}
      <article className="report-markdown">
        {reportText.split('\n').map((line, idx) => {
          if (line.startsWith('# ')) {
            return <h1 key={idx} style={{ marginTop: idx === 0 ? 0 : '1.5rem' }}>{line.replace('# ', '')}</h1>;
          } else if (line.startsWith('## ')) {
            return <h2 key={idx}>{line.replace('## ', '')}</h2>;
          } else if (line.startsWith('### ')) {
            return <h3 key={idx}>{line.replace('### ', '')}</h3>;
          } else if (line.startsWith('- ')) {
            return (
              <li key={idx} style={{ marginLeft: '1.5rem', listStyleType: 'disc', marginBottom: '0.3rem' }}>
                <span dangerouslySetInnerHTML={{ __html: line.replace('- ', '').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
              </li>
            );
          } else if (line.trim() === '') {
            return <div key={idx} style={{ height: '0.6rem' }} />;
          } else {
            return (
              <p key={idx} style={{ marginBottom: '0.5rem', color: '#e2e8f0' }}>
                <span dangerouslySetInnerHTML={{ __html: line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
              </p>
            );
          }
        })}
      </article>

      {/* Bottom Start New Interview CTA */}
      <div style={{ textAlign: 'center', marginTop: '3rem' }}>
        <button 
          className="btn btn-primary" 
          style={{ fontSize: '1.1rem', padding: '0.9rem 2.5rem', borderRadius: 'var(--radius-pill)' }}
          onClick={onResetSession}
        >
          <RotateCcw size={18} />
          <span>Practice Another Mock Interview</span>
        </button>
      </div>
    </section>
  );
}
